services:
  gateway:
    image: ronda-rshim-game-backend_gateway
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nats
    networks:
      - game-network

  game-engine:
    image: ronda-rshim-game-backend_game-engine
    build: ./services/game-engine
    ports:
      - "8081:8081"
    depends_on:
      - nats
    networks:
      - game-network

  nats:
    image: ronda-rshim-game-backend_nats
    build: ./services/nats
    ports:
      - "4222:4222"
    networks:
      - game-network

  # redis:
  #   image: ronda-rshim-game-backend_redis
  #   build: ./services/redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - game-network

networks:
  game-network:
    driver: bridge
